### ISSUE TITLE
Read gauge configuration variables in java

### ISSUE THREAD

**Issue by ghost** [getgauge-contrib/gauge-maven-plugin#17]
I need to read the env value am passing form command line in java.

My command line looks like :

mvn gauge:execute -DspecsDir=specs/e2e/Test.spec -Denv=DEV

Also i should be able to read the value from my pom

I tried the following code but its always giving null in both the cases

String env = System.getenv("env");
String prop = System.getProperty("env");

My pom.xml has the following:

<plugin>
    <groupId>com.thoughtworks.gauge.maven</groupId>
    <artifactId>gauge-maven-plugin</artifactId>
    <version>1.2.0</version>
    <executions>
        <execution>
            <phase>test</phase>
            <configuration>
                <specsDir>specs</specsDir>
                <env>QA</env>
            </configuration>
            <goals>
                <goal>execute</goal>
            </goals>
        </execution>
    </executions>
</plugin>

How do we read gauge-maven configurations in java?

**Comment by ajoecker** [comment]
That is not a gauge specific problem, but a maven one.

if you e.g. google `maven java access properties` you will find lots of information about that.

I hope that helps your use case

**Comment by haroon-sheikh** [comment]
@ghost
