### ISSUE TITLE
No specifications found in C:\Users\15512\IdeaProjects\gauge_selenium_maven\D:\spec\examples\example.spec.

### ISSUE THREAD

**Issue by JohnHuahuaZhan** [getgauge-contrib/gauge-maven-plugin#32]
when i tried to run "mvn test  -DspecsDir=D:/spec/examples/example.spec -Denv=default"
"No specifications found in C:\Users\15512\IdeaProjects\gauge_selenium_maven\D:\spec\examples\example.spec" error thrown. is the directory based on user.dir ?? i can not use absolute path

**Comment by sriv** [comment]
Yeah, gauge-maven plugin does not check for absolute path. [ref](https://github.com/getgauge/gauge-maven-plugin/blob/master/src/main/java/com/thoughtworks/gauge/maven/GaugeExecutionMojo.java#L224)

This is possible in gauge though, something like this works:

```
C:\Users\a\projects\gauge-visualstudio> gauge run C:\Users\a\AppData\Local\Temp\bar\specs\example.spec
```

**Comment by nehashri** [comment]
@JohnHuahuaZhan You can run Gauge specs from anywhere by specifying the correct maven project path.
Can you run the command 
```
mvn -f <path to project pom file> test -DspecsDir=D:/spec/examples/example.spec -Denv=default
```
and see if this works for you.
