### ISSUE TITLE
gauge maven plugin 1.3.0 is causing build failure

### ISSUE THREAD

**Issue by mittaadi** [getgauge-contrib/gauge-maven-plugin#56]
gauge maen plugin 1.4.0 is compiled with java 10 and gives unsupported format exception when trying to execute with java 8

**Comment by mittaadi** [comment]
Maven gauge plugin is giving org.apache.maven.lifecycle.LifecycleExecutionException: Gauge Specs execution failed .

**Comment by luciferankon** [comment]
@mittaadi Hey actually the version 1.4.0 doesn't support java8. Thanks.
