### ISSUE TITLE
Getting "Specs directory - does not exists." running mvn test command with gauge 1.0.8

### ISSUE THREAD

**Issue by manojTest** [getgauge-contrib/gauge-maven-plugin#60]
command ----- mvn test

[DEBUG]   (f) dir = /Users/Manoj/Downloads/Automation/
[DEBUG]   (f) env = api
[DEBUG]   (f) flags = [-]
[DEBUG]   (f) inParallel = true
[DEBUG]   (f) nodes = 2
[DEBUG]   (f) skip = false
[DEBUG]   (f) skipTests = false
[DEBUG]   (f) specsDir = specs
[DEBUG]   (f) tags = Api
[DEBUG] -- end configuration --
Specs directory - does not exists.

Caused by: org.apache.maven.plugin.MojoFailureException: Gauge Specs execution failed. null
    at com.thoughtworks.gauge.maven.GaugeExecutionMojo.execute (GaugeExecutionMojo.java:125)

gauge-maven-plugin 1.4.2

Gauge version: 1.0.8

Plugins
-------
html-report (4.0.10)
java (0.7.4)
screenshot (0.0.1)
spectacle (0.1.4)

openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)

Apache Maven 3.5.2

**Comment by zabil** [comment]
Can you try upgrading to 1.4.3

Also to confirm is `/Users/Manoj/Downloads/Automation/` a gauge project? How did you initialize the project?

**Comment by manojTest** [comment]
yes I have also tried 1.4.3

**Comment by manojTest** [comment]
This happen when we upgraded 1.0.8 from 1.0.7. Previouly work fine with 1.0.7

**Comment by manojTest** [comment]
it contains .gauge folder with following lastRunCommand.json 

[
	"gauge",
	"run",
	"--tags",
	"Api",
	"--parallel",
	"-n",
	"2",
	"--env",
	"api",
	"-",
	"--dir=/Users/Manoj/Downloads/Automation",
	"/Users/Manoj/Downloads/Automation/specs"
]

**Comment by zabil** [comment]
Please follow the instructions here
https://github.com/getgauge/gauge-java/issues/377#issue-567501356

To make sure everything is the latest version

**Comment by manojTest** [comment]
It is working fine with 1.0.7. we are facing issue with 1.0.8

**Comment by zabil** [comment]
I am unable to replicate this with the information provided.

Can you try initializing a new java project in that environment and try running it?
For example.

```
gauge init java_maven
mvn test // After changing directory to the newly created project.
```

If it does run, please refer the pom.xml if the newly generated project to see if there is difference with your project.

**Comment by manojTest** [comment]
Hi Zabil, Thanks a lot. I am able to identify the root cause. This is because of the flag we are passing to re-run the testases which work fine with 1.0.7. However breaking with 1.0.8.
I have removed it for now. as I don't need the test cases to re-run.

  <profiles>
    <profile>
        <id>apitest</id>
        <build>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.8.0</version>
                    <configuration>
                        <source>13</source>
                        <target>13</target>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>com.thoughtworks.gauge.maven</groupId>
                    <artifactId>gauge-maven-plugin</artifactId>
                    <version>1.4.2</version>
                    <executions>
                        <execution>
                            <id>test-api</id>
                            <phase>test</phase>
                            <configuration>
                                <env>api</env>
                                <specsDir>specs</specsDir>
                                <flags>-${run}</flags>
                            </configuration>
                            <goals>
                                <goal>execute</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </build>
    </profile>
   </profiles>

 Command we are using mvn test -Drun=  -Papitest
