### ISSUE TITLE
Feature request: Allow parallel "--only" option

### ISSUE THREAD

**Issue by DeltaIII** [getgauge-contrib/gauge-maven-plugin#68]
Hi,

It is currently not possible to use the parallel "--only" option ([documentation](https://docs.gauge.org/execution.html#run-specs-before-parallel-execution)) to run some gauge scenarios in parallel and all others sequentially due to the fact that `-Dflags` options is used in both the `verify` and `execute` goal.

Could you please add an argument, similar to `-Dnodes`, that can used to add the `--only "<tag_name>"`  to the gauge execution command?

**Comment by haroon-sheikh** [comment]
@DeltaIII you can configure the plugin like this:

```
<plugin>
	  <groupId>com.thoughtworks.gauge.maven</groupId>
	  <artifactId>gauge-maven-plugin</artifactId>
	  <executions>
	      <execution>
	          <id>execute</id>
	          <phase>test</phase>
	          <configuration>
	              <tags>${tags}</tags>
	              <specsDir>${specsDir}</specsDir>
	              <inParallel>true</inParallel>
	              <flags>
	                  <flag>--simple-console</flag>
	                  <flag>--only</flag>>
	                  <flag>${notParallelTags}</flag>
	              </flags>
	          </configuration>
	          <goals>
	              <goal>execute</goal>
	          </goals>
	      </execution>
	  </executions>
</plugin>
```
