### ISSUE TITLE
Moved to Gradle?

### ISSUE THREAD

**Issue by at6ue** [getgauge-contrib/gauge-maven-plugin#73]
> This plugin development now takes place here - https://github.com/getgauge/gauge-gradle-plugin

The link is for the gradle plugin.
Does this just mean that the project is moving to `getgauge` organization?
Or does it mean that the maven plugin will no longer be maintained?

**Comment by sriv** [comment]
Thanks for the catch. That was my bad. The banner was supposed to be in gauge-gradle 's older repo (https://github.com/getgauge-contrib/gauge-gradle-plugin)

The maven plugin is being developed here itself (i.e. https://github.com/getgauge-contrib/gauge-maven-plugin)

**Comment by at6ue** [comment]
Thank you so much!
