### ISSUE TITLE
Paralllel execution under the same suite

### ISSUE THREAD

**Issue by requizm** [getgauge-contrib/gauge-maven-plugin#75]
Hello. I'm trying to build with this command:

Lets say there is 1 suite(spec).
->suite1
--->tag1
--->tag2

If I run this command:
```
mvn clean compile test-compile gauge:execute -Dtags="tag1 | tag2" -DinParallel=true -Dnodes=2
```

There is no parallel run. Because they are under the same suite. Is it possible to run all tests in parallel, regardless of suite? Or am I missing something?

**Comment by i-whammy** [comment]
Hi @requizm ,

this page might be a clue for you.
https://docs.gauge.org/execution.html?os=linux&language=java&ide=vscode

It says
> Gauge sorts the specifications by alphabetical order and then distributes these specifications into groups.
so gauge will execute one spec(I meant a .spec file) in one group, and I guess therefore it is impossible to execute scenarios in  one spec in parallel.
